<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-10 18:05

$extensionPath = t3lib_extMgm::extPath('ics_bookmarks');
$extensionClassesPath = t3lib_extMgm::extPath('ics_bookmarks') . 'Classes/';
return array(
	'tx_icsbookmarks_libs' => $extensionClassesPath . 'class.tx_icsbookmarks_libs.php',
	'tx_icsbookmarks_manage' => $extensionClassesPath . 'class.tx_icsbookmarks_manage.php',
	'tx_icsbookmarks_iprovider' => $extensionClassesPath . 'interface.tx_icsbookmarks_IProvider.php',
	'tx_icsbookmarks_pi1' => $extensionPath . 'pi1/class.tx_icsbookmarks_pi1.php',
);
?>